[project]
name = "soft-cow-rasterization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kyk-web", email = "ky0063512@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "torch<2.12",
    "numpy",
    "pillow",
    "matplotlib",
    "tqdm",
    "imageio",
    "opencv-python>=4.13.0.92",
    "iopath>=0.1.10",
    "fvcore>=0.1.5.post20221221",
    "torchvision>=0.26.0",
]

[project.scripts]
soft-cow-rasterization = "soft_cow_rasterization:main"

[build-system]
requires = ["uv_build>=0.10.8,<0.11.0"]
build-backend = "uv_build"
